# Generated by Django 4.0.6 on 2022-07-23 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classif', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
    ]
